### ISSUE TITLE
plot_data() got an unexpected keyword argument 'save

### ISSUE THREAD

**Issue by harshagrao** [fstroth/findthetail#1] opened 2019-04-29 14:17 UTC
Hello, 
When i downloaded your example and was trying to run it locally on my system, i get this error when i try to load the data into model and run analyze. Can you please look into it?

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-4bb1ef74b529> in <module>()
      1 # instanciate the Ftt (Find the tail) class with data,
      2 # number of mc steps and a name for the report
----> 3 mod = ftt.Ftt(river_nidd_data['x'].values, mc_steps=500, data_name='River Nidd')
      4 mod.run_analysis()

C:\ProgramData\Anaconda3\lib\site-packages\findthetail\ftt.py in __init__(self, data, data_name, mc_steps)
     54 
     55         # plot the data before is is sorted and prepared
---> 56         self.plot_data(save='save')
     57         self.perpare_data()
     58 

TypeError: plot_data() got an unexpected keyword argument 'save'
```

**Comment by fstroth** [comment] 2019-04-30 14:56
Hey,

I'll have a look into it tomorrow.

**Comment by fstroth** [comment] 2019-05-01 12:12
The issue is now fixed. I'll update the pypi package later.

**Closed as completed by fstroth** 2019-05-01 12:12 UTC

**Comment by fstroth** [comment] 2019-05-01 21:23
The fixed version is now up on pipy.

**Comment by fstroth** [comment] 2019-05-01 21:40
The new version can now be downloaded via pypi.

**Comment by harshagrao** [comment] 2019-05-03 04:29
Thank you for the quick fix. It is working now.

Is it normal that it takes a lot of time for computation? I have a dataset which has 20,000 values and the analysis takes like an hour to finish :(. Any ideas how to speed it up?

**Comment by fstroth** [comment] 2019-05-03 14:53
I've released a new version which contains multiprocessing for the montecarlo simulation. That might help you, if you have used a large number of montecoarlo steps.

The problem is probably the fitting part. The algorithm hat to generate a possible tails so the fitting is done for a set of 2 data points up to a dataset of 20000 points, which inflates the number of data points used for the whole calculation to 199989999 points.
The fitting portion of the program should also be parallelizable, I might have a look into that over the weekend

**Comment by harshagrao** [comment] 2019-05-09 12:08
Sure. Thanks if that can be sped up too!
 It still takes many minutes even with 5000 rows to compute just the optimal tail. Its not the issue with the montecarlo steps which comes later if i understood your code correctly.
